# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kubeapps/ratesvc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce

      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure

      - run: go build -v
      - run: go test -v -race ./...
    
      - run: docker build -t kubeapps/ratesvc:latest .

      - deploy:
          name: Publish Docker Image
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" || -n "${CIRCLE_TAG}" ]]; then
              if [[ -n "${CIRCLE_TAG}" ]]; then
                docker tag kubeapps/ratesvc:latest kubeapps/ratesvc:${CIRCLE_TAG}
              fi
              docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
              docker push kubeapps/ratesvc
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9].*$/
